server:
  port: 8087

spring:
  application:
    name: realworld-service

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    #    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        #        format_sql: true
        use_sql_comments: true
  #      show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

#logging:
#  level:
#    org:
#      hibernate:
#        sql: debug
#        type: trace

